### ISSUE TITLE
Set up SonarQube analysis for this project

### ISSUE THREAD

**Issue by jpchip** [EarthlingInteractive/fssk-node#2]
EI has an internal SonarQube server: https://sonar.ei-app.com/

Set up SonarQube analysis for this project and tune the rules to healthy defaults.

This should include code coverage metrics via:
* Jest: https://github.com/EarthlingInteractive/fssk-laravel/tree/master/client#coverage-reporting

**Comment by sbrudz** [comment]
Resolved by #12
